### ISSUE TITLE
`--full-dump` doesn't seem to output anything.

### ISSUE THREAD

**Issue by aimzieslol** [evilsocket/nerve#13]
Installed the latest `cargo` build using:

```
cargo install nerve-ai
```

With my API keys defined as environment variables, if I run:

```
nerve -G groq://llama3-70b-8192 -T examples/fs_explorer/task.yml --full-dump
```

Not only do I not see any `PROMPT` messages but I don't see any extra created files or anything. If I specify a file it throws an error.

This is the output I see on the console:

```
nerve v0.0.3 🧠 llama3-70b-8192@groq > fs_explorer
task: read the file in /etc that contains mappings for hostnames to IP addresses and save its contents in your memory

<read-file> /etc/hosts -> 125 bytes
<memories> hosts-file-contents=127.0.1.1        nerve
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

task complete: 'The task is complete because I have successfully read the contents of the file in /etc that contains mappings for hostnames to IP addresses and saved its contents in my memory.'
```

FWIW, the `--stats` works to show timings, etc. I even tried using both `--stats` and `--full-dump` together and only saw stats.

**Comment by evilsocket** [comment]
As indicated here https://github.com/evilsocket/nerve?tab=readme-ov-file#how-does-it-work the argument you need to save to file is `--save-to FILENAME`, `--full-dump` only determines if that command will save everything or not, if you don't also pass --save-to it won't work.
