### ISSUE TITLE
http namespace cannot handle uri with body on POST, DELETE, PATCH, PUT method 

### ISSUE THREAD

**Issue by subhashdasyam** [evilsocket/nerve#17]
When running the web_vulnerability_scanner tasklet and trying to do the POST method for login or such kind of requests, nerve seem to fail as 
payload variable only contain the body of the form ( username and password ) but not the uri

the uri ( action ) is present in attr variable

see the below image 

![image](https://github.com/evilsocket/nerve/assets/19161628/5221981f-de8c-4006-b85e-b68287ee81d9)

FYI @evilsocket 

I have potential fix I will create the fix and reference the PR here

**Comment by evilsocket** [comment]
The action attribute is not supposed to be passed, that's the model hallucinating. If you check the cases where the payload is correctly passed, the POST works.

This (what the model provided) is wrong:

`<http-request action="/userinfo.php" method="POST"></http-request>`

It should be this instead:

`<http-request method="POST">/userinfo.php</http-request>` 

7/8B models do this, sometimes they provide wrong commands ... 70B are way more accurate.
