### ISSUE TITLE
some compilation issues macOS Sonoma

### ISSUE THREAD

**Issue by federico22285** [evilsocket/nerve#19]
Hey EvilSocket :-) 

Reporting here:

error[E0716]: temporary value dropped while borrowed
   --> crates/ollama-rs/src/generation/chat/mod.rs:204:26
    |
202 |           let chat_history = match self.messages_history.as_mut() {
    |               ------------ borrow later stored here
203 |               Some(history) => history,
204 |               None => &mut {
    |  __________________________^
205 | |                 let new_history =
206 | |                     std::sync::Arc::new(std::sync::RwLock::new(MessagesHistory::default()));
207 | |                 self.messages_history = Some(new_history);
208 | |                 self.messages_history.clone().unwrap()
209 | |             },
    | |             ^
    | |             |
    | |_____________temporary value is freed at the end of this statement
    |               creates a temporary value which is freed while still in use
    |
help: consider using a `let` binding to create a longer lived value
    |
202 ~         let binding = {
203 +                 let new_history =
204 +                     std::sync::Arc::new(std::sync::RwLock::new(MessagesHistory::default()));
205 +                 self.messages_history = Some(new_history);
206 +                 self.messages_history.clone().unwrap()
207 +             };
208 ~         let chat_history = match self.messages_history.as_mut() {
209 |             Some(history) => history,
210 ~             None => &mut binding,
    |

   Compiling memory-stats v1.1.0
For more information about this error, try `rustc --explain E0716`.
error: could not compile `ollama-rs` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
(base) ➜  nerve git:(main)

**Comment by aziis98** [comment]
I'm getting this same error, how did you solve this @federico22285?

EDIT: I used the rustc tip and that fixed the problem. This was wierd, maybe I'm not using the correct Rust version
