### ISSUE TITLE
openai://gpt-4 status 404

### ISSUE THREAD

**Issue by Sicks3c** [evilsocket/nerve#27]
Hello There

Thank you for the tool
I would like to point out that the openAI GPT4 configuration is not working properly on my end

![image](https://github.com/user-attachments/assets/0537ad0e-49d4-48c0-8b9d-a86020d9b22d)

I have the key `OPENAI_API_KEY` with `All` permissions set

**Comment by evilsocket** [comment]
Hi! I think it's something with your account / API key because I can use `openai://gpt-4` just fine:

![Screenshot 2024-12-05 alle 16 53 51](https://github.com/user-attachments/assets/5c86e174-6c36-41f4-8071-6ad839ca72c9)

**Comment by evilsocket** [comment]
Maybe relevant:

https://community.openai.com/t/gpt-4-api-access-granted-but-404-error/189881
